name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsqlite3-dev build-essential libgtest-dev
          # Build and install GTest
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Clean build directory
        run: rm -rf build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build all targets
        run: cmake --build build --parallel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-build
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install runtime dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: game-build
          path: build

      - name: Run Main Executable
        run: |
          echo "3" | ./build/main

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
